Repository OneulNail/OneulNail-server, pull requests merged in 2023-08, with the labels that each got.

#71 feat: Swagger 적용
  build.gradle
  src/main/java/com/example/oneulnail/domain/likePost/controller/LikePostController.java
  src/main/java/com/example/oneulnail/domain/likeStyle/controller/LikeStyleController.java
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/product/controller/ProductCotroller.java
  src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/user/controller/SignController.java
  src/main/java/com/example/oneulnail/global/config/OpenApiConfiguration.java
  src/main/java/com/example/oneulnail/global/config/SecurityConfig.java
  src/main/java/com/example/oneulnail/global/config/SwaggerConfig.java
  src/main/java/com/example/oneulnail/global/config/security/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller.java
  src/main/java/com/example/oneulnail/global/entity/BaseResponse.java
Labels: feature, 강재혁, fix

#72 [Feat/#70] cart 장바구니 생성,조회,삭제
  src/main/java/com/example/oneulnail/domain/cart/controller/CartController.java
  src/main/java/com/example/oneulnail/domain/cart/dto/request/CartAddReqDto.java
  src/main/java/com/example/oneulnail/domain/cart/dto/response/CartInfoResDto.java
  src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java
  src/main/java/com/example/oneulnail/domain/cart/mapper/CartMapper.java
  src/main/java/com/example/oneulnail/domain/cart/repository/CartRepository.java
  src/main/java/com/example/oneulnail/domain/cart/service/CartService.java
  src/main/java/com/example/oneulnail/global/config/SecurityConfig.java
Labels: feature, 윤서영

#73 [Feat/#59] 주문 생성 및 조회, 취소
  src/main/java/com/example/oneulnail/domain/cart/controller/CartController.java
  src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java
  src/main/java/com/example/oneulnail/domain/cart/repository/CartRepository.java
  src/main/java/com/example/oneulnail/domain/cart/service/CartService.java
  src/main/java/com/example/oneulnail/domain/order/controller/OrderController.java
  src/main/java/com/example/oneulnail/domain/order/dto/request/OrderRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/order/dto/response/OrderInfoResDto.java
  src/main/java/com/example/oneulnail/domain/order/dto/response/OrderRegisterResDto.java
  src/main/java/com/example/oneulnail/domain/order/entity/Order.java
  src/main/java/com/example/oneulnail/domain/order/entity/OrderStatus.java
  src/main/java/com/example/oneulnail/domain/order/mapper/OrderMapper.java
  src/main/java/com/example/oneulnail/domain/order/repository/OrderRepository.java
  src/main/java/com/example/oneulnail/domain/order/service/OrderService.java
  src/main/java/com/example/oneulnail/domain/post/entity/Post.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
  src/main/java/com/example/oneulnail/domain/product/dto/request/ProductRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/product/entity/Product.java
  src/main/java/com/example/oneulnail/domain/product/entity/ProductCategory.java
  src/main/java/com/example/oneulnail/domain/product/service/ProductService.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
Labels: feature, 윤서영, 이수용
