Repository OneulNail/OneulNail-server, pull requests merged in 2023-07, with the labels that each got.

#6 [Fix/#5] 패키지 수정
  src/main/java/com/example/oneulnail/common/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/oneulnail/common/config/security/JwtTokenProvider.java
  src/main/java/com/example/oneulnail/common/config/security/SecurityConfiguration.java
  src/main/java/com/example/oneulnail/user/controller/SignController.java
  src/main/java/com/example/oneulnail/user/controller/TestController.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignInReqDto.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignInResDto.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignUpReqDto.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignUpResDto.java
  src/main/java/com/example/oneulnail/user/entity/User.java
  src/main/java/com/example/oneulnail/user/repository/UserRepository.java
  src/main/java/com/example/oneulnail/user/service/SignService.java
  src/main/java/com/example/oneulnail/user/service/UserDetailsServiceImpl.java
Labels: 윤서영, fix

#7 [Fix/#3] JWT 회원가입 출력 값 수정 & TEST코드
  build.gradle
  src/main/java/com/example/oneulnail/common/config/security/JwtTokenProvider.java
  src/main/java/com/example/oneulnail/common/config/security/SecurityConfiguration.java
  src/main/java/com/example/oneulnail/common/constants/BaseResponseStatus.java
  src/main/java/com/example/oneulnail/user/controller/SignController.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignInResDto.java
  src/main/java/com/example/oneulnail/user/dto/sign/SignUpResDto.java
  src/main/java/com/example/oneulnail/user/entity/User.java
  src/main/java/com/example/oneulnail/user/repository/UserRepository.java
  src/main/java/com/example/oneulnail/user/service/SignService.java
  src/main/java/com/example/oneulnail/user/service/UserDetailsServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/example/oneulnail/OneulNailApplicationTests.java
  src/test/java/com/example/oneulnail/security/SecurityApplicationTests.java
Labels: 윤서영, fix

#16 feat: Shop 등록 기능 구현
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/shop/dto/request/ShopRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopRegisterResDto.java
  src/main/java/com/example/oneulnail/domain/shop/entity/Shop.java
  src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java
  src/main/java/com/example/oneulnail/domain/shop/repository/ShopRepository.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/OAuthAttributes.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/mapper/OAuth2SignUpMapper 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/CustomOAuth2UserService 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/userInfo/KakaoOAuth2UserInfo 2.java
Labels: feature, 강재혁

#17 hotfix: 오류 수정
  src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/mapper/OAuth2SignUpMapper 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/CustomOAuth2UserService 2.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/userInfo/KakaoOAuth2UserInfo 2.java
Labels: hotfix

#20 Feat/#15
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopRegisterResDto.java
Labels: feature, 강재혁, fix

#18 [Feat/#11] 회원가입 시 휴대폰 인증
  build.gradle
  src/main/java/com/example/oneulnail/domain/user/controller/SignController.java
  src/main/java/com/example/oneulnail/domain/user/dto/request/SignInReqDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/request/SignUpReqDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignInResDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignMessageResDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignUpResDto.java
  src/main/java/com/example/oneulnail/domain/user/service/SignService.java
Labels: feature, 윤서영

#21 feat: 단일 가게 조회 기능구현
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopFindOneResDto.java
  src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
Labels: feature, 강재혁

#23 feat: 전체 가게 조회 기능구현
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopListResDto.java
  src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java
  src/main/java/com/example/oneulnail/domain/shop/repository/ShopRepository.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
Labels: feature, 강재혁

#25 [Feat/#8 ] 선호 스타일 등록 기능 구현
  src/main/java/com/example/oneulnail/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/oneulnail/like_style/controller/LikeStyleController.java
  src/main/java/com/example/oneulnail/like_style/dto/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/LikeStyleResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/request/LikeStyleRegisterReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleFindReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleFindResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleRegisterResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleResDto.java
  src/main/java/com/example/oneulnail/like_style/entity/LikeStyle.java
  src/main/java/com/example/oneulnail/like_style/mapper/LikeStyleMapper.java
  src/main/java/com/example/oneulnail/like_style/repository/LikeStyleRepository.java
  src/main/java/com/example/oneulnail/like_style/service/LikeStyleService.java
  src/main/java/com/example/oneulnail/post/entity/Post.java
  src/main/java/com/example/oneulnail/post/entity/User.java
Labels: feature, 이수용

#27 Feat/#26
  src/main/java/com/example/oneulnail/domain/like_style/controller/LikeStyleController.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/request/LikeStyleRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/response/LikeStyleFindResDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/response/LikeStyleRegisterResDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/response/LikeStyleResDto.java
  src/main/java/com/example/oneulnail/domain/like_style/entity/LikeStyle.java
  src/main/java/com/example/oneulnail/domain/like_style/mapper/LikeStyleMapper.java
  src/main/java/com/example/oneulnail/domain/like_style/repository/LikeStyleRepository.java
  src/main/java/com/example/oneulnail/domain/like_style/service/LikeStyleService.java
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/post/dto/request/PostRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostRegisterResDto.java
  src/main/java/com/example/oneulnail/domain/post/entity/Post.java
  src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java
  src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/dto/OAuth2SignUpResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/LikeStyleResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleFindReqDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleFindResDto.java
  src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleResDto.java
  src/main/java/com/example/oneulnail/post/entity/Post.java
  src/main/java/com/example/oneulnail/post/entity/User.java
Labels: feature, 강재혁

#30 feat: 게시글 단일 조회
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostFindOneResDto.java
  src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
Labels: feature, 강재혁

#33 feat: 게시글 전체 조회
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostListResDto.java
  src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java
  src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
  src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
Labels: feature, 강재혁

#34 feat: Shop의 게시글 전체 조회
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostInfoResDto.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostListResDto.java
  src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java
  src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
Labels: feature, 강재혁

#36 feat: 카테고리별 게시글 조회
  src/main/java/com/example/oneulnail/domain/post/controller/PostController.java
  src/main/java/com/example/oneulnail/domain/post/dto/response/PostInfoResDto.java
  src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java
  src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
Labels: feature, 강재혁

#37 [Fix/#24] 자체 로그인/회원가입 구조 정리 & 에러처리
  src/main/java/com/example/oneulnail/domain/user/controller/SignController.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignInResDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignUpResDto.java
  src/main/java/com/example/oneulnail/domain/user/mapper/SignMapper.java
  src/main/java/com/example/oneulnail/domain/user/service/SignService.java
  src/main/java/com/example/oneulnail/global/constants/BaseResponseStatus.java
  src/main/java/com/example/oneulnail/global/entity/ExceptionAdvice.java
Labels: 윤서영, fix

#40 [Fix/#38] DTO 구조 정리
  src/main/java/com/example/oneulnail/domain/like_style/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/response/LikeStyleFindResDto.java
  src/main/java/com/example/oneulnail/domain/like_style/dto/response/LikeStyleResDto.java
Labels: hotfix, fix

#45 feat: 즐겨찾기한 게시글 조회
  src/main/java/com/example/oneulnail/domain/likePost/controller/LikePostController.java
  src/main/java/com/example/oneulnail/domain/likePost/repository/LikePostRepository.java
  src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java
Labels: feature, 강재혁

#48 Feat/#47 가게 예약 정보 조회
  src/main/java/com/example/oneulnail/domain/likePost/dto/request/LikePostRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/service/LikeStyleService.java
  src/main/java/com/example/oneulnail/domain/post/dto/request/PostRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
  src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/oneulnail/domain/reservation/dto/response/ReservationInfoResDto.java
  src/main/java/com/example/oneulnail/domain/reservation/mapper/ReservationMapper.java
  src/main/java/com/example/oneulnail/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
  src/main/java/com/example/oneulnail/domain/shop/dto/request/ShopRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
  src/main/java/com/example/oneulnail/domain/user/service/SignService.java
  src/main/java/com/example/oneulnail/global/config/security/jwt/service/JwtService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/dto/OAuth2SignUpReqDto.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/AuthService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/OAuth2SignUpService.java
Labels: feature, 강재혁, fix

#50 feat: 예약정보 전체 조회
  src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/oneulnail/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
Labels: feature, 강재혁

#53 Feat/#51 소셜 로그인 추가정보 등록하면 GUEST -> USER로 변경
  src/main/java/com/example/oneulnail/domain/user/entity/User.java
  src/main/java/com/example/oneulnail/global/config/security/jwt/service/JwtService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: 강재혁, fix

#55 Feat/#41 추천 네일 조회 및 선호스타일 등록 수정
  src/main/java/com/example/oneulnail/domain/likeStyle/controller/LikeStyleController.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleReqDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/response/LikeStyleFindResDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/dto/response/LikeStyleInfoResDto.java
  src/main/java/com/example/oneulnail/domain/likeStyle/entity/LikeStyle.java
  src/main/java/com/example/oneulnail/domain/likeStyle/repository/LikeStyleRepository.java
  src/main/java/com/example/oneulnail/domain/likeStyle/service/LikeStyleService.java
  src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java
  src/main/java/com/example/oneulnail/domain/post/service/PostService.java
Labels: feature, fix

#56 Feat/#54 상품,주문, 장바구니 Entity 생성
  src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java
  src/main/java/com/example/oneulnail/domain/order/entity/Order.java
  src/main/java/com/example/oneulnail/domain/product/entity/Product.java
Labels: feature, 윤서영, 강재혁

#57 hotfix: 외래키 수정 및 예약 등록 수정
  src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java
  src/main/java/com/example/oneulnail/domain/product/entity/Product.java
  src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/oneulnail/domain/reservation/entity/Reservation.java
  src/main/java/com/example/oneulnail/domain/reservation/mapper/ReservationMapper.java
  src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
Labels: hotfix

#60 [Feat/#58] 상품 등록 CRUD
  src/main/java/com/example/oneulnail/domain/product/controller/ProductCotroller.java
  src/main/java/com/example/oneulnail/domain/product/dto/request/ProductRegisterReqDto.java
  src/main/java/com/example/oneulnail/domain/product/dto/response/ProductInfoResDto.java
  src/main/java/com/example/oneulnail/domain/product/dto/response/ProductRegisterResDto.java
  src/main/java/com/example/oneulnail/domain/product/entity/Product.java
  src/main/java/com/example/oneulnail/domain/product/mapper/ProductMapper.java
  src/main/java/com/example/oneulnail/domain/product/repository/ProductRepository.java
  src/main/java/com/example/oneulnail/domain/product/service/ProductService.java
  src/main/java/com/example/oneulnail/global/config/security/SecurityConfig.java
Labels: feature, 윤서영

#64 feat: Docker 설정
  Dockerfile
  docker-compose.yml
  src/main/java/com/example/oneulnail/domain/order/entity/Order.java
Labels: feature, 강재혁

#67 [Feat/#61] 자체로그인 refreshToken생성
  build.gradle
  src/main/java/com/example/oneulnail/domain/user/controller/SignController.java
  src/main/java/com/example/oneulnail/domain/user/dto/request/SignUpReqDto.java
  src/main/java/com/example/oneulnail/domain/user/dto/response/SignInResDto.java
  src/main/java/com/example/oneulnail/domain/user/entity/RefreshToken.java
  src/main/java/com/example/oneulnail/domain/user/mapper/SignMapper.java
  src/main/java/com/example/oneulnail/domain/user/repository/RedisRepository.java
  src/main/java/com/example/oneulnail/domain/user/repository/UserRepository.java
  src/main/java/com/example/oneulnail/domain/user/service/SignService.java
  src/main/java/com/example/oneulnail/global/config/RedisConfig.java
  src/main/java/com/example/oneulnail/global/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/oneulnail/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/oneulnail/global/config/security/JwtTokenProvider.java
  src/main/java/com/example/oneulnail/global/config/security/SecurityConfig.java
  src/main/java/com/example/oneulnail/global/constants/BaseResponseStatus.java
Labels: feature, 윤서영

#65 Feat/#63 Resolver 설정 및 @LoginUser 구현
  src/main/java/com/example/oneulnail/domain/likePost/controller/LikePostController.java
  src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java
  src/main/java/com/example/oneulnail/domain/likeStyle/controller/LikeStyleController.java
  src/main/java/com/example/oneulnail/domain/likeStyle/service/LikeStyleService.java
  src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java
  src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
  src/main/java/com/example/oneulnail/global/annotation/LoginUser.java
  src/main/java/com/example/oneulnail/global/config/WebConfig.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/AuthService.java
  src/main/java/com/example/oneulnail/global/config/security/oauth2/service/OAuth2SignUpService.java
  src/main/java/com/example/oneulnail/global/resolver/LoginUserArgumentResolver.java
Labels: feature, 강재혁, fix
